version: '3.3'
services:
  collaboration-server:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "${SERVER_PORT}:8181"
  postgres:
    image: postgres:13.1
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "cs"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db: